repos:
  # -----------------------------
  # Basic repo hygiene
  # -----------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  # -----------------------------
  # Terraform
  # -----------------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.0
    hooks:
      - id: terraform_fmt
     # - id: terraform_validate

  # -----------------------------
  # Terragrunt
  # -----------------------------
  - repo: local
    hooks:
      - id: terragrunt_fmt
        name: terragrunt hcl fmt
        entry: terragrunt hcl fmt
        language: system
        files: \.hcl$
      #- id: terragrunt_validate
       # name: terragrunt validate
       # entry: terragrunt validate
       # language: system
       # files: terragrunt\.hcl$
       # pass_filenames: false
